version: '3'
services:
  docker-spawner:
    build: .
    container_name: docker-spawner
    volumes: 
      - gitlab_artifacts:/usr/src/app/artifacts
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  gitlab_artifacts:
    external: true